// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

// En développement on charge les .env locaux. En production (Coolify, etc.)
// les variables sont injectées directement dans l'environnement.
if (process.env.NODE_ENV !== "production") {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { config } = require("dotenv");
  config({ path: ".env.local" });
  config({ path: ".env" });
}

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
